In [ ]:
pip install emoji

In [ ]:
import tensorflow as tf


In [ ]:
import numpy as np
import pandas as pd
import emoji

from keras.models import Sequential
from keras.layers import Dense, LSTM, SimpleRNN, Embedding

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.utils import to_categorical


In [ ]:
data = pd.read_csv('/content/emoji_data.csv', header = None)
data.head()

0  1
0  French macaroon is so tasty  4
1             work is horrible  3
2                   I am upset  3
3               throw the ball  1
4                    Good joke  2

In [ ]:
emoji_dict ={
    0: ":red_heart:",
    1: ":baseball:",
    2: ":grinning_face_with_big_eyes:",
    3: ":disappointed_face:",
    4: ":fork_and_knife_with_plate:"
}

def label_to_emoji(label):
  return emoji.emojize(emoji_dict[label])



In [ ]:
X = data[0].values
Y = data[1].values
X

array(['French macaroon is so tasty', 'work is horrible', 'I am upset',
       'throw the ball', 'Good joke',
       'what is your favorite baseball game', 'I cooked meat',
       'stop messing around', 'I want chinese food',
       'Let us go play baseball', 'you are failing this exercise',
       'yesterday we lost again', 'Good job', 'ha ha ha it was so funny',
       'I will have a cheese cake', 'Why are you feeling bad',
       'I want to joke', 'I never said yes for this',
       'the party is cancelled', 'where is the ball', 'I am frustrated',
       'ha ha ha lol', 'she said yes', 'he got a raise',
       'family is all I have', 'he can pitch really well',
       'I love to the stars and back', 'do you like pizza ',
       'You totally deserve this prize', 'I miss you so much',
       'I like your jacket ', 'she got me a present',
       'will you be my valentine', 'you failed the midterm',
       'Who is down for a restaurant', 'valentine day is near',
       'Great so awesome

In [ ]:
# embedding
file = open('/content/glove.6B.100d.txt','r',encoding = 'utf8')
content = file.readlines()


In [ ]:
embeddings = {}
for line in content:
  line = line.split()
  embeddings[line[0]] = np.array(line[1:], dtype = float)

print(len(embeddings) )


15895


In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X)
word2index = tokenizer.word_index
word2index

{'i': 1,
 'you': 2,
 'is': 3,
 'the': 4,
 'a': 5,
 'so': 6,
 'am': 7,
 'my': 8,
 'to': 9,
 'this': 10,
 'are': 11,
 'ha': 12,
 'for': 13,
 'she': 14,
 'he': 15,
 'me': 16,
 'not': 17,
 'love': 18,
 'your': 19,
 'want': 20,
 'have': 21,
 'it': 22,
 'got': 23,
 'like': 24,
 'did': 25,
 'baseball': 26,
 'food': 27,
 'was': 28,
 'do': 29,
 'joke': 30,
 'stop': 31,
 'will': 32,
 'miss': 33,
 'life': 34,
 'ball': 35,
 'good': 36,
 'what': 37,
 'go': 38,
 'job': 39,
 'funny': 40,
 'bad': 41,
 'day': 42,
 'great': 43,
 'dinner': 44,
 'that': 45,
 'with': 46,
 'at': 47,
 'of': 48,
 'game': 49,
 'we': 50,
 'again': 51,
 'said': 52,
 'yes': 53,
 'lol': 54,
 'and': 55,
 'down': 56,
 'had': 57,
 'her': 58,
 'fun': 59,
 'smile': 60,
 'lot': 61,
 'working': 62,
 'him': 63,
 'cute': 64,
 'on': 65,
 'lets': 66,
 'messing': 67,
 'us': 68,
 'play': 69,
 'exercise': 70,
 'lost': 71,
 'never': 72,
 'where': 73,
 'can': 74,
 'well': 75,
 'much': 76,
 'valentine': 77,
 'restaurant': 78,
 'awesome': 79,
 'lik

In [ ]:
print(len(word2index))

312


In [ ]:
Xtokens = tokenizer.texts_to_sequences(X)

In [ ]:
# making all tokens of same length
def get_maxlen(data):
  maxlen = 0
  for sent in data:
    maxlen = max(maxlen, len(sent))
  return maxlen

maxlen = get_maxlen(Xtokens)





In [ ]:
Xtrain = pad_sequences(Xtokens, maxlen = maxlen, padding = 'post', truncating = 'post')



In [ ]:
Xtrain

array([[103, 104,   3, ...,   0,   0,   0],
       [106,   3, 107, ...,   0,   0,   0],
       [  1,   7, 108, ...,   0,   0,   0],
       ...,
       [ 14,   3,   5, ...,   0,   0,   0],
       [ 14, 310,  26, ...,   0,   0,   0],
       [  1,  24,  22, ...,   0,   0,   0]], dtype=int32)

In [ ]:
Ytrain = to_categorical(Y)
Ytrain

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0.

In [ ]:
embed_size = 100
embedding_matrix = np.zeros((len(word2index)+1, embed_size))

for word, i in word2index.items():
  # Check if word is present in embeddings before accessing
  if word in embeddings:
    embed_vector = embeddings[word]
    embedding_matrix[i] = embed_vector
  else:
    # Handle words not found in embeddings (e.g., assign a random vector)
    embedding_matrix[i] = np.random.rand(embed_size) # or any other strategy

In [ ]:
embedding_matrix

array([[ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
         0.      ],
       [-0.046539,  0.61966 ,  0.56647 , ..., -0.37616 , -0.032502,
         0.8062  ],
       [-0.49886 ,  0.76602 ,  0.89751 , ..., -0.41179 ,  0.40539 ,
         0.78504 ],
       ...,
       [-0.46263 ,  0.069864,  0.69095 , ..., -0.29174 ,  0.32041 ,
         0.21202 ],
       [ 0.073242,  0.11134 ,  0.62281 , ...,  0.53417 , -0.1646  ,
        -0.27516 ],
       [ 0.29019 ,  0.80497 ,  0.31187 , ..., -0.33603 ,  0.45998 ,
        -0.11278 ]])

In [ ]:
#model creation

model = Sequential([
    Embedding(input_dim = len(word2index)+1,
              output_dim = embed_size,
              input_length = maxlen,
              weights = [embedding_matrix],
              trainable = False
              ),
    LSTM(units = 16, return_sequences= True), # return sequences return values at every time stamp
    LSTM(units = 4),
    Dense(5, activation ='softmax')
])

model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.fit(Xtrain, Ytrain, epochs = 100)

Epoch 1/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.2055 - loss: 1.6050
Epoch 2/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.2978 - loss: 1.5875
Epoch 3/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.2631 - loss: 1.5782
Epoch 4/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.2293 - loss: 1.5687
Epoch 5/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.2834 - loss: 1.5584
Epoch 6/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.3509 - loss: 1.5329
Epoch 7/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.3601 - loss: 1.5131
Epoch 8/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.3712 - loss: 1.5031
Epoch 9/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4395 - loss: 1.4775
Epoch 10/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5163 - loss: 1.4402
Epoch 11/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4885 - loss: 1.4279
Epoch 12/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5276 - lo

In [ ]:
test = ["I feel good", "I feel very bad", "Lets eat dinner"]
test_seq = tokenizer.texts_to_sequences(test)
test_pad = pad_sequences(test_seq, maxlen = maxlen, padding = 'post', truncating = 'post')

y_pred = model.predict(test_pad)
y_pred = np.argmax(y_pred, axis = 1)

for i in range(len(test)):
  print(test[i], label_to_emoji(y_pred[i]) )


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
I feel good 😃
I feel very bad 😞
Lets eat dinner 🍽️
